# This is a basic workflow to help you get started with Actions

name: Link PR to Jira

on:
  pull_request:
    types: [opened, edited]

jobs:
  link-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for Jira Ticket in PR title or branch
        id: jira-check
        run: |
          TICKET_PATTERN="[A-Z]{2,5}-[0-9]{1,5}"
          TITLE="${{ github.event.pull_request.title }}"
          BRANCH="${{ github.event.pull_request.head.ref }}"
          
          if [[ "$TITLE" =~ $TICKET_PATTERN ]]; then
            echo "Jira ticket found in PR title: ${BASH_REMATCH[0]}"
            echo "::set-output name=jira_ticket::${BASH_REMATCH[0]}"
          elif [[ "$BRANCH" =~ $TICKET_PATTERN ]]; then
            echo "Jira ticket found in branch name: ${BASH_REMATCH[0]}"
            echo "::set-output name=jira_ticket::${BASH_REMATCH[0]}"
          else
            echo "No Jira ticket found."
          fi
      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "Linked Jira Ticket: ${{ steps.jira-check.outputs.jira_ticket }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           

